### ISSUE TITLE
Typescript fails to compile on v2.9.4

### ISSUE THREAD

**Issue by Zelec123** [Nicklason/tf2-automatic#290]
When compiling the latest tagged release, tsc reports that the tsconfig.json file doesn’t exist

**To Reproduce**

1. git checkout v2.9.4
2. npm install
3. tsc -p .

**Expected behavior**
No output, and the creation of the dist folder

**Screenshots and logs**
```
[user@tf2-automatic app]$ tsc -p .
error TS5057: Cannot find a tsconfig.json file at the specified directory: '.'.
```

**Additional context**
My automated docker builds at [Gitlab](https://gitlab.com/Zelec/docker-tf2/automatic) run weekly, rather than just pulling master it checks out the latest tagged release to lower the amount of bugs that could slip through.

Version: v2.9.4

**Comment by Zelec123** [comment]
Issue related to v2 not needing typescript compilation, Closing.
